# Backend https://decapcms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: "Creating {{collection}} “{{slug}}”"
    update: "Updating {{collection}} “{{slug}}”"
    delete: "Deleting {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Uploading “{{path}}”"
    deleteMedia: "[skip ci] Deleting “{{path}}”"

# Publish mode https://decapcms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://decapcms.org/docs/configuration-options/#media-and-public-folders
media_folder: public/images
public_folder: /images

# Collections https://decapcms.org/docs/configuration-options/#collections
collections:
  - label: Blog
    name: blog
    label_singular: 'Post'
    folder: blog
    format: frontmatter
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Show Last Updated, name: lastUpdated, widget: boolean, required: false, default: false }
      - { label: Featured Image, name: featuredImage, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }